In [19]:
#Create an array using the method 1. array 2. arange 3. linspace

#array method

import array as a
_intarr = a.array('i', [1,2,3,4,5])
for arrv in _intarr:
    print (arrv)

#arange method
import numpy as np
print(np.arange(3))

#linespace
print(np.linspace(2,10,10))

1
2
3
4
5
[0 1 2]


array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [25]:
#Identify the shape and dimensions of an array

import numpy as np
arr = np.array([[2.,  2.88888889],[3.77777778,  4.66666667], [5.55555556, 6.44444444],[7.33333333,  8.22222222]])
print('Dimension is {} and shape is {}'.format(arr.ndim, arr.shape))

Dimension is 2 and shape is (4, 2)


In [34]:
#Replace the values which are multiples of 5 by -1 using fancy indexing in [1,5,10,4,15,20,7,35]

arr = np.array([1,5,10,4,15,20,7,35])
mask = (arr%5 == 0)
arr[mask] = -1
print(arr)

[ 1 -1 -1  4 -1 -1  7 -1]


In [45]:
#Create a array and find out the sum of the elements

arr = np.random.randint(100,size=(10,2))
print(arr.sum())

826


In [57]:
#Reshape an array np.array([1, 2, 3, 4], ndmin=2) using ravel and identify the shape, dimensions and write your conclusions

arr = np.array([1, 2, 3, 4], ndmin=2)
print(arr.shape)
print(arr.ravel().shape)
print(arr.ravel().ndim)

(1, 4)
(4,)
1


In [67]:
# How to remove from one array those items that exist in another? a = np.array([1, 2, 3, 4, 5]) b = np.array([5, 6, 3, 1, 4])

a = np.array([1, 2, 3, 4, 5]) 
b = np.array([5, 6, 3, 1, 4])

np.intersect1d(a,b)

array([1, 3, 4, 5])